// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTp8yyijhF5HB1dWH_q4rqVrQKRJMU-1s',
    appId: '1:1042898914437:web:367ddb735735727c52edec',
    messagingSenderId: '1042898914437',
    projectId: 'chemisphere-a054a',
    authDomain: 'chemisphere-a054a.firebaseapp.com',
    databaseURL: 'https://chemisphere-a054a-default-rtdb.firebaseio.com',
    storageBucket: 'chemisphere-a054a.appspot.com',
    measurementId: 'G-7ZY8X2L3Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTnxPDFagbFjNqAxOwTNcA7MQABQpr22Q',
    appId: '1:1042898914437:android:4b2b2c4a102c91c152edec',
    messagingSenderId: '1042898914437',
    projectId: 'chemisphere-a054a',
    databaseURL: 'https://chemisphere-a054a-default-rtdb.firebaseio.com',
    storageBucket: 'chemisphere-a054a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj9P58cKZM3Uv_Fdt4MXZ4VSEmx1X_bH8',
    appId: '1:1042898914437:ios:eca8369a1c53c69e52edec',
    messagingSenderId: '1042898914437',
    projectId: 'chemisphere-a054a',
    databaseURL: 'https://chemisphere-a054a-default-rtdb.firebaseio.com',
    storageBucket: 'chemisphere-a054a.appspot.com',
    iosBundleId: 'com.example.educationWebAdminPanel',
  );

}